[package]
authors = ["joniaiuser <64962001+joniaiuser@users.noreply.github.com>"]
edition = "2018"
name = "variables"
version = "2.3.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
